# Default values for {{cookiecutter.project_slug}}
# This is a YAML-formatted file.

# Global configuration
global:
  environment: production

# Replica count
replicaCount: 1

# Image configuration
image:
  repository: {{cookiecutter.project_slug}}-app
  tag: latest
  pullPolicy: IfNotPresent

# Build arguments for Docker
buildArgs:
  APP_ENV: prod
  ENABLE_TESTING: false
  ENABLE_LINTING: false
  ENABLE_DEBUG: false
  ENABLE_PRE_COMMIT: false

# Service configuration
service:
  type: ClusterIP
  port: {{cookiecutter.api_port}}
  targetPort: {{cookiecutter.api_port}}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: {{cookiecutter.project_slug}}.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m

# Environment variables
env: []

# Development configuration
dev:
  enabled: false
  service:
    port: {{cookiecutter.api_port}}
    targetPort: {{cookiecutter.api_port}}
  buildArgs:
    APP_ENV: dev
    ENABLE_TESTING: true
    ENABLE_LINTING: true
    ENABLE_DEBUG: true
    ENABLE_PRE_COMMIT: false
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m

# Production configuration
prod:
  enabled: true
  service:
    port: {{cookiecutter.api_port}}
    targetPort: {{cookiecutter.api_port}}
  buildArgs:
    APP_ENV: prod
    ENABLE_TESTING: false
    ENABLE_LINTING: false
    ENABLE_DEBUG: false
    ENABLE_PRE_COMMIT: false
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m 